name = input('Enter your name: ')
dobD = int(input('Enter your DOB Day: '))
dobM = int(input('Enter your DOB Month: '))
dobY = int(input('Enter your DOB Year: '))
strEnc = input('Enter your String: ')